### ISSUE TITLE
JaegerRemoteSamplerTest is flaky. (Fail 5x)

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#1275]
see https://circleci.com/gh/open-telemetry/opentelemetry-java/4241 or
https://circleci.com/gh/open-telemetry/opentelemetry-java/4259 for example

```
> Task :opentelemetry-sdk-contrib-jaeger-remote-sampler:test
Picked up _JAVA_OPTIONS: -Xmx3g

io.opentelemetry.sdk.contrib.trace.jaeger.sampler.JaegerRemoteSamplerTest > description FAILED
    java.lang.AssertionError: Resource ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=9, target=directaddress:///my-service}} can not be released in time at the end of test
        at io.grpc.testing.GrpcCleanupRule.teardown(GrpcCleanupRule.java:169)
        at io.grpc.testing.GrpcCleanupRule.access$100(GrpcCleanupRule.java:48)
        at io.grpc.testing.GrpcCleanupRule$1.evaluate(GrpcCleanupRule.java:138)
```

Re-running the build usually helps but this should be fixed.

Tracking instances:
https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/2325/workflows/8072b109-a9cd-4313-adcc-7304d4d51d49/jobs/4731/steps

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java/2335/workflows/c823a3cc-0c48-45db-ae87-646be91f033a/jobs/4754

**Comment by pavolloffay** [comment]
I will have a look at this

**Comment by arminru** [comment]
Thanks, Pavol! It's nice to have someone available in my timezone 😄

**Comment by pavolloffay** [comment]
@arminru could you please review? https://github.com/open-telemetry/opentelemetry-java/pull/1276

**Comment by jkwatson** [comment]
This is still breaking occasionally. reopening.

**Comment by jarebudev** [comment]
i can take a look if noone is already

**Comment by jarebudev** [comment]
I had a look into this.  It looks like there's a potential race condition in this test, although I couldn't recreate locally so have no proof :)

The ```JaegerRemoteSamplerTest.description``` test builds a ```JaegerRemoteSampler```, and checks that the description of the sampler is the expected default sampling strategy before exiting the test method.  The ```GrpcCleanupRule``` will then run and shutdown the gRPC resources.

The ```JaegerRemoteSampler``` constructor starts a separate thread to periodically retrieve the sampling strategy.  I expect in most cases the ```GrpcCleanupRule``` happens before the thread to fetch sampling strategy starts, and you see the following stderr

```
Jun 21, 2020 11:51:39 AM io.opentelemetry.sdk.extensions.trace.jaeger.sampler.JaegerRemoteSampler$1 run
WARNING: Failed to update sampler
io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
	at io.opentelemetry.exporters.jaeger.proto.api_v2.SamplingManagerGrpc$SamplingManagerBlockingStub.getSamplingStrategy(SamplingManagerGrpc.java:169)
	at io.opentelemetry.sdk.extensions.trace.jaeger.sampler.JaegerRemoteSampler.getAndUpdateSampler(JaegerRemoteSampler.java:96)
	at io.opentelemetry.sdk.extensions.trace.jaeger.sampler.JaegerRemoteSampler.access$000(JaegerRemoteSampler.java:43)
	at io.opentelemetry.sdk.extensions.trace.jaeger.sampler.JaegerRemoteSampler$1.run(JaegerRemoteSampler.java:73)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
``` 

However there is a chance that the ```GrpcCleanupRule``` may be attempting to clean up the registered server and channel at the same time the separate executing thread is trying to use the channel.  I'm not an authority on gRPC so I don't know if there's potential for problems here, but it doesn't seem desirable to me.

I've got a PR which will prevent the test method from exiting until the sampling strategy is retrieved  #1364 

Suggest we try this fix and see if it resolves this?

**Comment by thisthat** [comment]
Closing the issue since it looks like #1364 did its job! I don't see the build fail for quite some time :wink:

**Comment by pavolloffay** [comment]
thanks @jarebudev for fixing this!
