### ISSUE TITLE
Cannot use OTLP exporter on native builds via Graal

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-java#1645]
**Describe the bug**
When building a native binary for an application using GraalVM, the OTLP exporter fails with:

```
java.lang.IllegalArgumentException: cannot find a NameResolver for localhost:55680
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:723)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:605)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:517)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter$Builder.build(OtlpGrpcSpanExporter.java:284)
	at io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.getDefault(OtlpGrpcSpanExporter.java:168)
```

**Steps to reproduce**
1. created a new [Quarkus](https://quarkus.io/) application
1. configured dependencies
1. configured a tracer with the OTLP exporter
1. confirmed that everything works as expected via `./gradlew quarkusDev`
1. `./gradlew build -Dquarkus.package.type=native` works too
1. running the generated binary causes the exception above

**What version and what artifacts are you using?**
Artifacts: 
```
    implementation 'io.opentelemetry:opentelemetry-api:0.8.0'
    implementation 'io.opentelemetry:opentelemetry-sdk:0.8.0'
    implementation 'io.opentelemetry:opentelemetry-exporters-otlp:0.8.0'
    implementation 'io.grpc:grpc-okhttp:1.31.1'
```
**Environment**
Compiler: 
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
```

OS: `Fedora release 32 (Thirty Two)`

**Comment by jpkrohling** [comment]
Reproducer: https://github.com/jpkrohling/opentelemetry-generate-span-java

**Comment by iNikem** [comment]
Thank you for this bug report! :) Our first from Quarkus!

I see [this comment](https://github.com/grpc/grpc-java/issues/1982#issuecomment-228845231) and thinking maybe you have to configure GraalVM compiler in the same way? To allow SPI to work.

**Comment by jkwatson** [comment]
@jpkrohling is this still an issue? Have you been able to try the suggestion for compiler configuration?

**Comment by jpkrohling** [comment]
> maybe you have to configure GraalVM compiler in the same way?

Sorry, but I'm unable to find what I need to do there. If I'm reading it correctly, the linked issue seems only to talk about the cause.
