### ISSUE TITLE
JaegerIntegrationTest failure

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1816]
Started getting this bizarre exception locally, not sure why I haven't seen it before. It seems we are initializing Groovy in some of our tests :O Will try to remove RestAssured

```
io.opentelemetry.exporters.jaeger.JaegerIntegrationTest > testJaegerIntegration() FAILED
    java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
        at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.createMetaMethodFromClass(MetaClassRegistryImpl.java:258)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:111)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.createMap(ScriptBytecodeAdapter.java:635)
        at io.restassured.internal.ResponseParserRegistrar.<init>(ResponseParserRegistrar.groovy)
        at io.restassured.RestAssured.<clinit>(RestAssured.java:347)
        at io.opentelemetry.exporters.jaeger.JaegerIntegrationTest.assertJaegerHaveTrace(JaegerIntegrationTest.java:88)
```

**Comment by jkwatson** [comment]
:yikes: ! Who let groovy in the house!?
