### ISSUE TITLE
Nameresolver not found when using forTarget

### ISSUE THREAD

**Issue by johnbowdenatfacet** [open-telemetry/opentelemetry-java#2331]
Hi,

When i connect to the back end using host and port, everything works.  When I use an endpoint uri e.g.

`ManagedChannel jaegerChannel = ManagedChannelBuilder.forTarget( configFile.getProperty( "jaeger.endpoint" ) ).usePlaintext().build();`

I get the following error:

```
java.lang.IllegalArgumentException: cannot find a NameResolver for http://localhost:14268/api/traces
java.lang.IllegalArgumentException: cannot find a NameResolver for http://localhost:14268/api/traces
	at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:729)
	at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:609)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
```

Just after a solution to fix this.

Cheers,
John

**Comment by jkwatson** [comment]
This seems like more of a grpc configuration issue than anything opentelemetry specific. Have you tried looking for grpc issues around this exception?

**Comment by johnbowdenatfacet** [comment]
Sorry, I have used with the host/port which was fine.  I see a "nameResolverFactory" method, trying to use this with the default "new NameResolver.Factory()" though having difficulty.  Would there be any examples using the forTarget implementation?

**Comment by anuraaga** [comment]
@johnbowdenatfacet It's a pretty confusing error message indeed - you can't pass a scheme or path to that method. It should be "localhost:14268". Is your Jaeger actually using gRPC? I don't think `/api/traces` is a path used with gRPC.

**Comment by johnbowdenatfacet** [comment]
Thanks @anuraaga I had some left overs from testing with the OpenTracing package.  Though now I'm getting the following error:
`io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter$1 onFailure
WARNING: Failed to export spans
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
`

**Comment by anuraaga** [comment]
Hi @johnbowdenatfacet, I'm not that familiar with Jaeger but I did a quick scan and found this

https://www.jaegertracing.io/docs/1.19/apis/#thrift-over-http-stable

It seems like your old URL http://localhost:14268/api/traces is for the thrift endpoint, so presuambly your Jaeger server is only accepting that, not gRPC (hence HTTP/2 exception). Can you try the Jaeger thrift exporter instead?

https://github.com/open-telemetry/opentelemetry-java/tree/master/exporters/jaeger-thrift

**Comment by anuraaga** [comment]
@johnbowdenatfacet We updated the README in #2339 does it solve your issue?
