### ISSUE TITLE
Bad user experience if metrics is not on the classpath

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2941]
If you use the auto-configure module, but don't want metrics, and don't have it on your classpath, you get a big, ugly error when you start up: 

```
Exception in thread "main" io.opentelemetry.sdk.autoconfigure.ConfigurationException: OTLP Metrics Exporter enabled but opentelemetry-exporter-otlp-metrics not found on classpath. Make sure to add it as a dependency to enable this feature.
	at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:15)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureOtlpMetrics(MetricExporterConfiguration.java:53)
	at io.opentelemetry.sdk.autoconfigure.MetricExporterConfiguration.configureExporter(MetricExporterConfiguration.java:27)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.configureMeterProvider(OpenTelemetrySdkAutoConfiguration.java:61)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:42)
```

We shouldn't fail to start up the app if the user doesn't have any intention to have metrics enabled. Until metrics is stable, our auto-configuration module probably shouldn't default to `otlp` as the exporter.

Current workaround is: `-Dotel.metrics.exporter=none`, but it's a hassle to make the user do that.

**Comment by bogdandrutu** [comment]
Can we make `-Dotel.metrics.exporter=none` to be default?

**Comment by jkwatson** [comment]
> Can we make `-Dotel.metrics.exporter=none` to be default?

I think this is exactly what we should do, until metrics is stable. 👍

**Comment by anuraaga** [comment]
We could also squash and ignore if it's not on the classpath for metrics, that would technically follow the current spec better I guess.
