### ISSUE TITLE
Otel Collector excessive logging 

### ISSUE THREAD

**Issue by rgidwani-splunk** [open-telemetry/opentelemetry-java#3013]
**Describe the bug**
```[opentelemetry.auto.trace 2021-03-11 06:31:57:789 +0000] [BatchSpanProcessor_WorkerThread-1] WARN io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter - Failed to export spans
io.jaegertracing.internal.exceptions.SenderException: Could not send 2 spans, response 400: invalid character '\f' looking for beginning of value

	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:86)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.lambda$export$2(JaegerThriftSpanExporter.java:102)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.export(JaegerThriftSpanExporter.java:96)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:262)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:203)
	at java.lang.Thread.run(Thread.java:748)```

If the collector crash loops, it fills up the logs with this.  Making the logs pretty unreadable.

**Comment by jkwatson** [comment]
I've added this to the 1.1.0 milestone. Would love a volunteer to help make the logging more useful and less spammy when things are going poorly with the collector.
