### ISSUE TITLE
Alternative queue implementation that does not use the `jdk.unsupported` module

### ISSUE THREAD

**Issue by brunojcm** [open-telemetry/opentelemetry-java#3339]
**Is your feature request related to a problem? Please describe.**
The current version of `opentelemetry-java` (1.3.0 as of this bug report) requires the `jdk.unsupported` JDK module to be included if one is using `jlink` to build a custom JDK. This is not a sustainable approach.

**Describe the solution you'd like**
Provide a config that allows a `BatchSpanProcessor` to be created using another `Queue<ReadableSpan>` implementation that does not rely on unsupported modules.

**Describe alternatives you've considered**
I'm currenlty adding `jdk.unsupported`, but I need to have a plan to remove those eventually. `opentelemetry-java` is my biggest dependency that requires `jdk.unsupported`.

**Comment by anuraaga** [comment]
Hi @brunojcm - can you confirm that with jdk.unsupported not included, you get an exception from here?

https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/util/UnsafeAccess.java#L71

We could probably catch exceptions and fallback to `ArrayBlockingQueue` here instead of adding extra knobs if so

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace-shaded-deps/src/main/java/io/opentelemetry/sdk/trace/internal/JcTools.java#L18

**Comment by brunomed** [comment]
(brunojcm here, using my other account to reply)

That is the full stacktrace:
```
[otel.javaagent 2021-06-22 05:21:27:988 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.3.0
[otel.javaagent 2021-06-22 05:21:28:177 +0000] [main] INFO io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:56)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.getUnsafe(UnsafeAccess.java:54)
	at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.<clinit>(UnsafeAccess.java:44)
	at io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.<clinit>(MpscArrayQueue.java:48)
	at io.opentelemetry.sdk.trace.internal.JcTools.newMpscArrayQueue(JcTools.java:19)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:75)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:141)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureSpanProcessor(TracerProviderConfiguration.java:95)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureSpanProcessor(TracerProviderConfiguration.java:68)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:54)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:40)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.runBeforeAgentListeners(AgentInstaller.java:171)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:114)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:97)
	... 13 more
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.findClass(AgentClassLoader.java:165)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at io.opentelemetry.javaagent.bootstrap.AgentClassLoader.loadClass(AgentClassLoader.java:146)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more"
```

**Comment by brunomed** [comment]
Raised https://github.com/open-telemetry/opentelemetry-java/pull/3340 for that

**Comment by brunomed** [comment]
PR is merged, how do we deal with this ticket?

**Comment by anuraaga** [comment]
Ah thanks we usually add Fixes into a PR description so can close this manually now. Will go out in our next monthly release.
