### ISSUE TITLE
opentelemetry-exporter-jaeger not found on classpath.

### ISSUE THREAD

**Issue by chengtangzheng2021** [open-telemetry/opentelemetry-java#3399]
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
Jaeger gRPC Exporter enabled but opentelemetry-exporter-jaeger not found on classpath. Make sure to add it as a dependency to enable this feature.
	at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:15)

**What version and what artifacts are you using?**
javaagent 1.3

**Environment**
java 8

**Additional context**

**Comment by jkwatson** [comment]
I'm sorry. What is the bug here?

**Comment by chengtangzheng2021** [comment]
otel.traces.exporter=jaeger
opentelemetry-javaagent-1.3.0.jar
with this parameter, run javaagent version 1.3 got the exporter not found error, run with 1.2 is good,
run with otel.traces.exporter=otlp
also got its exporter not found error

**Comment by chengtangzheng2021** [comment]
[otel.javaagent 2021-07-14 18:42:55:941 -0400] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.3.0
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:56)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: io.opentelemetry.sdk.autoconfigure.ConfigurationException: Jaeger gRPC Exporter enabled but opentelemetry-exporter-jaeger not found on classpath. Make sure to add it as a dependency to enable this feature.
	at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:15)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureJaeger(SpanExporterConfiguration.java:107)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:45)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:51)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:40)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeAgent(OpenTelemetryInstaller.java:27)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.runBeforeAgentListeners(AgentInstaller.java:171)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:114)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:97)

**Comment by jkwatson** [comment]
Is the jaeger exporter on your classpath?

**Comment by anuraaga** [comment]
Hi @chengtangzheng2021 - it looks like you are using the java agent. Can you make sure you are using a `-all` agent, for example the one from our release notes?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.3.1

The vanilla version contains no exporters.
