### ISSUE TITLE
More information on how to implement in android

### ISSUE THREAD

**Issue by juliandavid333** [open-telemetry/opentelemetry-java#3438]
I don't see much documentation on how to implement it in android, neither blogs nor communities, I don't find much info.

like [this](https://opentelemetry.io/docs/swift/)

**Comment by Oberon00** [comment]
I think nobody we know of has tried it & reported back so far. Did you try it and hit any roadblocks?

**Comment by jkwatson** [comment]
Splunk is using otel extensively in our new RUM instrumentation for Android. There isn't really much special about it. It pretty well works out of the box as it should.

Have you had any issues @juliandavid333 ?

**Comment by jkwatson** [comment]
FYI: https://github.com/signalfx/splunk-otel-android

**Comment by juliandavid333** [comment]
> FYI: https://github.com/signalfx/splunk-otel-android

thank you, let me try

**Comment by kylannjohnson** [comment]
I've been experimenting with version 1.6.0 on Android and, since our min API level is 23, it fails at runtime with this exception. 

```
                         E  java.lang.NoClassDefFoundError: io.opentelemetry.api.common.ArrayBackedAttributes$$ExternalSyntheticLambda0
                         E      at io.opentelemetry.api.common.ArrayBackedAttributes.<clinit>(ArrayBackedAttributes.java:20)
                         E      at io.opentelemetry.api.common.Attributes$-CC.of(Attributes.java:62)
                         E      ...
```

The [static method](https://developer.android.com/reference/java/util/Comparator#comparing(java.util.function.Function%3C?%20super%20T,%20?%20extends%20U%3E)) isn't support on Android until API 24.

Is the min API of 24 a hard minimum?  What other APIs are only on 24 that this library is depending on?  Just looking to get more clarification on the minimum.

**Comment by jkwatson** [comment]
I see. But, your example stack trace was specifically about static methods on interfaces.  :) Are you saying that for API level 21-24, you can only target Java 8 language level in your build, and it will work, without desugaring?

**Comment by ankitnayan** [comment]
@kylannjohnson were you able to make it work for android?

@jkwatson what changes will be needed to make `splunk-otel-android` send data to `jaeger`? I see the readme mention something like below

```
    private final Config config = SplunkRum.newConfigBuilder()
            .realm(realm)
            .rumAccessToken(rumAccessToken)
            .applicationName("My Android App")
            .build();
```
