### ISSUE TITLE
opencensus-shim flaky test

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3450]
I don't understand the opencensus metrics shim enough to try to unflake this with an awaitility or something. @jsuereth is this something you could check (or just delete the metrics shim? :-)?

```
InteroperabilityTest > testSupportedMetricsExportedCorrectly() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 4
    but was : 2
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at io.opentelemetry.opencensusshim.InteroperabilityTest.testSupportedMetricsExportedCorrectly(InteroperabilityTest.java:419)
```

**Comment by anuraaga** [comment]
@jsuereth If you could take a look at this would be great, thanks!

**Comment by jsuereth** [comment]
@anuraaga How can I check stability after the latest test fixes?

I noticed this before and I think the move to Awaitility should (mostly) resolve the issue.

**Comment by anuraaga** [comment]
If we have reason to believe it might be fixed now, we close. And if it resurfaces we repoen. Wouldn't be a flaky test if it was easy to verify ;)
