### ISSUE TITLE
NPE: CompletableResultCode.ofAll invoked with null by MultiSpanExporter.shutdown

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3497]
A build of f2cb03395c91781ba9b6f92091af1f0a8dc413fd in #3466 failed in CI (macos-latest, 17) with this unrelated NPE:

```
> Task :sdk:trace:test

BatchSpanProcessorTest > exporterThrowsException() FAILED
    java.lang.NullPointerException: Cannot invoke "io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(java.lang.Runnable)" because "code" is null
        at io.opentelemetry.sdk.common.CompletableResultCode.ofAll(CompletableResultCode.java:48)
        at io.opentelemetry.sdk.trace.export.MultiSpanExporter.shutdown(MultiSpanExporter.java:94)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.lambda$shutdown$2(BatchSpanProcessor.java:268)
        at io.opentelemetry.sdk.common.CompletableResultCode.whenComplete(CompletableResultCode.java:126)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.shutdown(BatchSpanProcessor.java:265)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.access$200(BatchSpanProcessor.java:125)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.shutdown(BatchSpanProcessor.java:110)
        at io.opentelemetry.sdk.trace.TracerSharedState.shutdown(TracerSharedState.java:96)
        at io.opentelemetry.sdk.trace.SdkTracerProvider.shutdown(SdkTracerProvider.java:115)
        at io.opentelemetry.sdk.trace.export.BatchSpanProcessorTest.cleanup(BatchSpanProcessorTest.java:69)
```

(from https://github.com/open-telemetry/opentelemetry-java/pull/3466#issuecomment-896829706)

**Comment by anuraaga** [comment]
@Oberon00 Did you see it after? I intended to fix in https://github.com/open-telemetry/opentelemetry-java/pull/3469 (sorry for not linking to you)

**Comment by Oberon00** [comment]
No, I just created the bug ticket now based on that comment. I didn't see that PR.

**Comment by anuraaga** [comment]
Cool we should be good then thanks
