### ISSUE TITLE
LocalCacheFactory fails if `jdk.unsupported` module is not available

### ISSUE THREAD

**Issue by brunojcm** [open-telemetry/opentelemetry-java#3605]
**Is your feature request related to a problem? Please describe.**
The current version of opentelemetry-java (1.5.3 as of this bug report) requires the `jdk.unsupported` JDK module to be included if one is using `jlink` to build a custom JDK. This is not a sustainable approach.

The following error occurs:
```
[otel.javaagent 2021-09-11 08:20:50:638 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.5.3
[otel.javaagent 2021-09-11 08:20:50:911 +0000] [main] INFO io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
    at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:51)
    at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:44)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
    at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.UnsafeAccess.load(UnsafeAccess.java:66)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.UnsafeAccess.&lt;clinit&gt;(UnsafeAccess.java:40)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.BLCHeader$DrainStatusRef.&lt;clinit&gt;(BoundedLocalCache.java:3931)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Unknown Source)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:87)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.&lt;init&gt;(BoundedLocalCache.java:3387)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.&lt;init&gt;(BoundedLocalCache.java:3383)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.internal.shaded.caffeine.cache.Caffeine.build(Caffeine.java:1079)
    at io.opentelemetry.javaagent.shaded.instrumentation.api.caching.CacheBuilder.build(CacheBuilder.java:71)
    at io.opentelemetry.javaagent.tooling.muzzle.AgentCachingPoolStrategy.&lt;init&gt;(AgentCachingPoolStrategy.java:58)
    at io.opentelemetry.javaagent.tooling.muzzle.AgentTooling.&lt;clinit&gt;(AgentTooling.java:15)
    at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:129)
    at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:97)
```

**Describe the solution you'd like**
I would like to be able to run `opentelemetry-java` with a custom built JDK that does NOT include

**Describe alternatives you've considered**
I'm currenlty adding `jdk.unsupported`, but I need to have a plan to remove those eventually. `opentelemetry-java` is my biggest dependency that requires `jdk.unsupported`.

**Comment by brunojcm** [comment]
This is a follow-up of https://github.com/open-telemetry/opentelemetry-java/issues/3339

**Comment by brunojcm** [comment]
This is on the instrumentation code base, reported https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4092 instead.
