### ISSUE TITLE
Autoconfigure requires otlp/grpc even if OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL is set to http/protobuf

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3633]
It seems to require OTEL_EXPERIMENTAL_EXPORTER_OTLP_TRACES_PROTOCOL (with TRACES_).

This was with 1.6.0, so sorry if it has been fixed since.

Exception message logged:

```
Error automatically configuring OpenTelemetry SDK. OpenTelemetry will not be enabled.
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: OTLP gRPC Trace Exporter enabled but opentelemetry-exporter-otlp not found on classpath. Make sure to add it as a dependency to enable this feature.
	at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:17)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureOtlp(SpanExporterConfiguration.java:128)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:86)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.lambda$configureSpanExporters$1(SpanExporterConfiguration.java:78)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:75)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:52)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:65)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:45)
	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.opentelemetry.api.GlobalOpenTelemetry.maybeAutoConfigure(GlobalOpenTelemetry.java:171)
	at io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:57)
	at io.opentelemetry.api.GlobalOpenTelemetry.getTracer(GlobalOpenTelemetry.java:111)
	...(application frames)...
```

CC @jack-berg

**Comment by jack-berg** [comment]
Yikes that's not good. Will take a look.

**Comment by jack-berg** [comment]
@Oberon00 - I wasn't able to recreate this.

I ran a test app depending on `v1.6.0` and a dependency on `io.opentelemetry:opentelemetry-exporter-otlp-http-trace` (no dependency on `io.opentelemetry:opentelemetry-exporter-otlp-trace`. 

I was able to successfully autoconfigure and export data to the collector using both:
```
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL=http/protobuf
```
and
```
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces
OTEL_EXPERIMENTAL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
```

I also double checked the `testOtlpHttpImplementation` test set in `:sdk-extensions:autoconfigure` and it should be testing the scenario you describe:
- It [depends](https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/build.gradle.kts#L64-L68) on `:exporters:otlp-http:trace` and `:exporters:otlp-http:metrics` (and no dependency on the grpc exporters
- [Here](https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java#L166) it tests the `otel.experimental.exporter.otlp.protocol` config
- And [here](https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/src/testOtlpHttp/java/io/opentelemetry/sdk/autoconfigure/OtlpHttpConfigTest.java#L223) it tests that `otel.experimental.exporter.otlp.traces.protocol` has higher precedence

Can you double check your config? The error message you show [can only be reached](https://github.com/open-telemetry/opentelemetry-java/blob/v1.6.0/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java#L127) if the protocol is resolved to be `grpc` based on the env vars / system properties.

**Comment by Oberon00** [comment]
I tried and could not reproduce it either. This probably means that I was forgetting to recompile or made a similarly stupid mistake. Sorry for wasting your time! 🙈
