### ISSUE TITLE
Ran JaegerExample but got exception - UnsupportedOperationException: Only available on DefaultGrpcExporter

### ISSUE THREAD

**Issue by zbhuang2008** [open-telemetry/opentelemetry-java#4040]
**Describe the bug**
I tried to run opentelemetry-java/examples/jaeger. I followed the steps described here, 
https://github.com/open-telemetry/opentelemetry-java/tree/main/examples/jaeger
In step3, when run this command, "java -cp build/libs/opentelemetry-examples-jaeger-0.1.0-SNAPSHOT-all.jar io.opentelemetry.example.jaeger.JaegerExample localhost 14250",
I got the following error
Exception in thread "main" java.lang.UnsupportedOperationException: Only available on DefaultGrpcExporter
 at io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporterBuilder.setChannel(OkHttpGrpcExporterBuilder.java:55)
 at io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporterBuilder.setChannel(OkHttpGrpcExporterBuilder.java:31)
 at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.setChannel(JaegerGrpcSpanExporterBuilder.java:51)
 at io.opentelemetry.example.jaeger.ExampleConfiguration.initOpenTelemetry(ExampleConfiguration:40)
 at io.opentelemetry.example.jaeger.JaegerExample.main(JaegerExample:44)

**What version and what artifacts are you using?**
openTelemetryVersion = "1.9.1"
https://github.com/open-telemetry/opentelemetry-java/blob/main/examples/build.gradle

**Environment**
Compiler: (e.g., "AdoptOpenJDK 16.0.1+9")
OS: (e.g., "macOS Big Sur  version 11.6.1")

**Additional context**

**Comment by jack-berg** [comment]
Thanks for reporting!

The example configuration is missing a dependency on `io.grpc:grpc-stub`. See PR #4041 for a fix.

**Comment by zbhuang2008** [comment]
Nice, tested it and it is working now. Thanks.
