### ISSUE TITLE
Flaky test: sdk:metrics:test

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#4042]
https://github.com/open-telemetry/opentelemetry-java/actions/runs/1638390189/attempts/1

```
> Task :sdk:metrics:test

SdkDoubleHistogramTest > boundDoubleHistogramRecord_MonotonicityCheck() FAILED
    org.opentest4j.AssertionFailedError: Contain the string <Histograms can only record non-negative values. Instrument testHistogram has recorded a negative value.> ==> None of the 0 captured log events matched the filter predicate
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:134)
        at app//io.github.netmikey.logunit.api.LogCapturer.lambda$assertContains$3(LogCapturer.java:174)
        at java.base@11.0.11/java.util.Optional.orElseGet(Optional.java:369)
        at app//io.github.netmikey.logunit.api.LogCapturer.assertContains(LogCapturer.java:173)
        at app//io.github.netmikey.logunit.api.LogCapturer.assertContains(LogCapturer.java:121)
        at app//io.opentelemetry.sdk.metrics.SdkDoubleHistogramTest.boundDoubleHistogramRecord_MonotonicityCheck(SdkDoubleHistogramTest.java:208)
```

**Comment by jack-berg** [comment]
I tried to recreate this locally after I saw it in the build, but wasn't able to. Will try a few more things.

**Comment by jack-berg** [comment]
I haven't seen this since originally reported. Want to keep this issue open or close?
