### ISSUE TITLE
1.10.0-alpha metrics PrometheusCollector error

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java#4099]
`
Caused by: java.lang.IllegalStateException: No collection info for handle, this is a bug in the OpenTelemetry SDK.
	at io.opentelemetry.sdk.metrics.SdkMeterProvider$LeasedMetricProducer.collectAllMetrics(SdkMeterProvider.java:158) ~[opentelemetry-sdk-metrics-1.10.0-alpha.jar:1.10.0]
	at io.opentelemetry.exporter.prometheus.PrometheusCollector.collect(PrometheusCollector.java:35) ~[opentelemetry-exporter-prometheus-1.10.0-alpha.jar:1.10.0]
	at io.prometheus.client.CollectorRegistry.collectorNames(CollectorRegistry.java:113) ~[simpleclient-0.12.0.jar:na]
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:50) ~[simpleclient-0.12.0.jar:na]
	at io.prometheus.client.Collector.register(Collector.java:308) ~[simpleclient-0.12.0.jar:na]
	at io.prometheus.client.Collector.register(Collector.java:301) ~[simpleclient-0.12.0.jar:na]
	at io.opentelemetry.exporter.prometheus.PrometheusCollector$Factory.apply(PrometheusCollector.java:76) ~[opentelemetry-exporter-prometheus-1.10.0-alpha.jar:1.10.0]
	at io.opentelemetry.sdk.metrics.SdkMeterProvider.<init>(SdkMeterProvider.java:84) ~[opentelemetry-sdk-metrics-1.10.0-alpha.jar:1.10.0]
	at io.opentelemetry.sdk.metrics.SdkMeterProviderBuilder.build(SdkMeterProviderBuilder.java:140) ~[opentelemetry-sdk-metrics-1.10.0-alpha.jar:1.10.0]
`

Like above, the latest 1.10.0-alpha version occur error, but the 1.9.1-alpha version not. There is a bug from the new version?

**Comment by yangtaoran** [comment]
Hi @jack-berg, the `PrometheusCollector ` default not registry to `CollectorRegistry.defaultRegistry`?

**Comment by jack-berg** [comment]
@yangtaoran the `PrometheusCollector` does register to the `CollectoRegistry.defaultRegistry`. 

This issue should be resolved in the [1.10.1](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.10.1) patch release.
