### ISSUE TITLE
LongGaugeBuilder interface method buildWithCallback used but not implemented

### ISSUE THREAD

**Issue by sigma-libra** [open-telemetry/opentelemetry-java#4159]
**Describe the bug**
Since version 1.10.0, when we attempt to use the BatchSpanProcessor for tracing with a ZipkinSpanExporter as follows:

```
 SpanExporter exporter = ZipkinSpanExporter.builder().setEndpoint(url).build()
 SpanProcessor spanProcessor = BatchSpanProcessor.builder(exporter).build()
```
we get the following error:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.ObservableLongGauge io.opentelemetry.api.metrics.LongGaugeBuilder.buildWithCallback(java.util.function.Consumer)'
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:187)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:140)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:80)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:147)
```

When replacing the BatchSpanProcessor with a SimpleSpanProcessor, but using the same exporter, the issue disappears.

**What did you expect to see?**
A successfully built BatchSpanProcessor, as in v1.9.1

**What did you see instead?**
```
Exception in thread "main" java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.ObservableLongGauge io.opentelemetry.api.metrics.LongGaugeBuilder.buildWithCallback(java.util.function.Consumer)'
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:187)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.<init>(BatchSpanProcessor.java:140)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:80)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:147)
```

**What version and what artifacts are you using?**
Artifacts: 
  implementation(platform("io.opentelemetry:opentelemetry-bom:1.11.0"))
  implementation("io.opentelemetry:opentelemetry-exporter-zipkin")
  implementation("io.opentelemetry:opentelemetry-api")
  implementation("io.opentelemetry:opentelemetry-extension-trace-propagators")
  implementation("org.http4k:http4k-core")
  implementation("org.http4k:http4k-server-undertow")
  implementation("org.http4k:http4k-format-kotlinx-serialization")
  implementation("org.http4k:http4k-client-apache")
  implementation("org.http4k:http4k-opentelemetry")
  
Version: 1.11.0, but also occurs in 1.10.0
How did you reference these artifacts? `build.gradle`

**Comment by jkwatson** [comment]
This sounds like you might have an older version of the metrics API on your classpath somewhere. Can that you only have v1.11.0 versions of everything?

**Comment by sigma-libra** [comment]
If you're referring to io.opentelemetry.api.metrics, then yes, it's using v1.11.0. For example I tried manually setting the MeterProvider to GlobalMeterProvider, as it was in December:

`
import io.opentelemetry.api.metrics.GlobalMeterProvider
import io.opentelemetry.api.metrics.MeterProvider
BatchSpanProcessor.builder(exporter).setMeterProvider(GlobalMeterProvider.get()).build()`

This still produces the same error. The packaged library has version v.1.11.0.

**Comment by jkwatson** [comment]
Can you put together a small bit of sample code that reproduces this? I still believe that your classpath has some old artifacts on it, since the method referenced there definitely exists in the current metrics API.

**Comment by anuraaga** [comment]
@sigma-libra I'm not completely sure but can you try `enforcedPlatform` instead of `platform`? I guess it may be picking up an older version transitively through http4k, I think enforced will fix transitive versions too.

Note that you will make sure you are not using any of `http4k`'s metrics functionality until they update to newer opentelemetry. It looks like they included our alpha artifacts in their stable (?) artifact so chaos is expected.

**Comment by sigma-libra** [comment]
Thanks. Unfortunately enforcedPlatform does not work, since as you correctly deduced we are also using the http4k-opentelemetry library, which it turns out is bringing in a bunch of openetelemetry:v1.6 dependencies. I'll close this bug and go see them about updating their dependencies, and if the issue persists after that I'll be back.

Thank you for your help!

**Comment by sigma-libra** [comment]
Update: http4k is updated to use the more recent versions of opentelemetry as of http4k 4.19.3.0.
