### ISSUE TITLE
Flaky test: PeriodicMetricReaderTest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#4322]
https://github.com/open-telemetry/opentelemetry-java/runs/5764576433?check_suite_focus=true

```
> Task :sdk:metrics:test

SdkObservableInstrumentTest > close() STANDARD_ERROR
    [Test worker] WARN io.opentelemetry.sdk.metrics.SdkObservableInstrument - Instrument my-instrument has called close() multiple times.

PeriodicMetricReaderTest > periodicExport_NoMetricsSkipsExport() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting value to be true but was false
        at sun.reflect.GeneratedConstructorAccessor12.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.opentelemetry.sdk.metrics.export.PeriodicMetricReaderTest.periodicExport_NoMetricsSkipsExport(PeriodicMetricReaderTest.java:128)
```

**Comment by jack-berg** [comment]
Will watch for this to happen again. It might have been fixed by a recent merge.

**Comment by jack-berg** [comment]
Closing because I believe this was fixed and hasn't happened again.
