### ISSUE TITLE
Flaky test: RetryInterceptorTest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#4461]
https://github.com/open-telemetry/opentelemetry-java/runs/6390524772?check_suite_focus=true

```
RetryInterceptorTest > connectTimeout() FAILED
    org.mockito.exceptions.verification.TooFewActualInvocations: 
    object.apply(<any>);
    Wanted 5 times:
    -> at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest$1.apply(RetryInterceptorTest.java:61)
    But was 1 time:
    -> at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest$1.apply(RetryInterceptorTest.java:58)
        at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest$1.apply(RetryInterceptorTest.java:61)
        at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest$1.apply(RetryInterceptorTest.java:58)
        at io.opentelemetry.exporter.internal.retry.RetryInterceptorTest.connectTimeout(RetryInterceptorTest.java:154)
```

**Comment by laurit** [comment]
This is similar to https://github.com/open-telemetry/opentelemetry-java/issues/4407 https://github.com/open-telemetry/opentelemetry-java/blob/b7b6a75637300e3a6ab6eb1551c84f6e6fa43854/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/internal/retry/RetryInterceptor.java#L100-L106 does not consider `SocketTimeoutException` as retryable.
