### ISSUE TITLE
OTel SDK autoconfigure non-String system property

### ISSUE THREAD

**Issue by fax4ever** [open-telemetry/opentelemetry-java#4543]
If a non-String system property is present on the Java system, we get this error:

``` bash
2022-06-17 16:34:00,688 WARN  (main) [org.infinispan.server.core.RequestTracer] OpenTelemetry tracer cannot be configured java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at io.opentelemetry.sdk.autoconfigure.DefaultConfigProperties.lambda$new$2(DefaultConfigProperties.java:59)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at java.base/java.util.Properties.forEach(Properties.java:1422)
	at io.opentelemetry.sdk.autoconfigure.DefaultConfigProperties.<init>(DefaultConfigProperties.java:57)
	at io.opentelemetry.sdk.autoconfigure.DefaultConfigProperties.get(DefaultConfigProperties.java:40)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.getConfig(AutoConfiguredOpenTelemetrySdkBuilder.java:389)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:305)
	at org.infinispan.server.core.RequestTracer.<clinit>(RequestTracer.java:23)
```

**Comment by jack-berg** [comment]
Resolved in #4544.
