### ISSUE TITLE
OtlpGrpcRetryTest test flake

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4624]
Noticed a test flake [here](https://github.com/open-telemetry/opentelemetry-java/runs/7431610099?check_suite_focus=true#step:5:1436):

```

OtlpGrpcRetryTest > configureLogExporterRetryPolicy() FAILED
    org.opentest4j.AssertionFailedError: [status code PERMISSION_DENIED should make 1 requests] 
    expected: 1
     but was: 0
        at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base@11.0.15/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at app//io.opentelemetry.sdk.autoconfigure.OtlpGrpcRetryTest.testRetryableStatusCodes(OtlpGrpcRetryTest.java:133)
        at app//io.opentelemetry.sdk.autoconfigure.OtlpGrpcRetryTest.configureLogExporterRetryPolicy(OtlpGrpcRetryTest.java:105)
```

**Comment by breedx-splk** [comment]
Have we seen this happen again?

**Comment by jack-berg** [comment]
Not that i've noticed.
