### ISSUE TITLE
[jaeger-thrift exporter] JaegerThriftSpanExporter remains in broken state when UDP message size is exceeded

### ISSUE THREAD

**Issue by nevenamanova** [open-telemetry/opentelemetry-java#4662]
**Describe the bug**
We are using the following span exporter configuration
```
        UdpSender thriftSender = new UdpSender(agentHostname,
                                               agentPort,
                                               ThriftUdpTransport.MAX_PACKET_SIZE);
        SpanExporter exporter = JaegerThriftSpanExporter.builder()
            .setThriftSender(thriftSender).build();
        BatchSpanProcessor
            .builder(exporter)
            .build();
```
This configuration uses default values for batch size etc. This combination though disregards the fact that the UdpSeder also has a a message size limit. It is possible to easily overflow this limit, when for example the batch processor tries to send 204 spans at once each of a size ~320 bytes. Here is what we see:
```
WARNING: Failed to export spans
io.jaegertracing.internal.exceptions.SenderException: Could not send 204 spans
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:86)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.lambda$export$2(JaegerThriftSpanExporter.java:99)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.export(JaegerThriftSpanExporter.java:93)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:320)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Message size too large: 55 > 65000
	at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.write(ThriftUdpTransport.java:135)
	at org.apache.thrift.protocol.TCompactProtocol.writeString(TCompactProtocol.java:367)
	at io.jaegertracing.thriftjava.Tag$TagStandardScheme.write(Tag.java:905)
	at io.jaegertracing.thriftjava.Tag$TagStandardScheme.write(Tag.java:809)
	at io.jaegertracing.thriftjava.Tag.write(Tag.java:709)
	at io.jaegertracing.thriftjava.Span$SpanStandardScheme.write(Span.java:1360)
	at io.jaegertracing.thriftjava.Span$SpanStandardScheme.write(Span.java:1144)
	at io.jaegertracing.thriftjava.Span.write(Span.java:1028)
	at io.jaegertracing.thriftjava.Batch$BatchStandardScheme.write(Batch.java:473)
	at io.jaegertracing.thriftjava.Batch$BatchStandardScheme.write(Batch.java:407)
	at io.jaegertracing.thriftjava.Batch.write(Batch.java:344)
	at io.jaegertracing.agent.thrift.Agent$emitBatch_args$emitBatch_argsStandardScheme.write(Agent.java:1056)
	at io.jaegertracing.agent.thrift.Agent$emitBatch_args$emitBatch_argsStandardScheme.write(Agent.java:1018)
	at io.jaegertracing.agent.thrift.Agent$emitBatch_args.write(Agent.java:969)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:71)
	at org.apache.thrift.TServiceClient.sendBaseOneway(TServiceClient.java:66)
	at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:70)
	at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:84)
	... 6 more
```
The bigger issue here is that after such an error, the ThriftUdpTransport buffer is not cleaned up as the error is not handled properly. When such an error occurs, it is unrecoverable - no more spans can ever be sent out. Every attempt fails with an error simlar to: 
```
WARNING: Failed to export spans
io.jaegertracing.internal.exceptions.SenderException: Could not send 6 spans
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:86)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.lambda$export$2(JaegerThriftSpanExporter.java:99)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.export(JaegerThriftSpanExporter.java:93)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:320)
	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: Message size too large: 1 > 65000
	at io.jaegertracing.thrift.internal.reporters.protocols.ThriftUdpTransport.write(ThriftUdpTransport.java:135)
	at org.apache.thrift.protocol.TCompactProtocol.writeByteDirect(TCompactProtocol.java:482)
	at org.apache.thrift.protocol.TCompactProtocol.writeMessageBegin(TCompactProtocol.java:208)
	at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:70)
	at org.apache.thrift.TServiceClient.sendBaseOneway(TServiceClient.java:66)
	at io.jaegertracing.agent.thrift.Agent$Client.send_emitBatch(Agent.java:70)
	at io.jaegertracing.agent.thrift.Agent$Client.emitBatch(Agent.java:63)
	at io.jaegertracing.thrift.internal.senders.UdpSender.send(UdpSender.java:84)
	... 6 more
```
The ask is not to fix the jaeger-thrift client, as I know it is already deprecated, but to handle properly the error and flush the buffer so that even when this happens next batch will be sent.

**Steps to reproduce**
- Configure a BatchSpanProcessor with a UdpSender and default values, as described above
- The application  should create enough spans to overflow the buffer limit of 65000 bytes

**What did you expect to see?**
The exporter should be able to recover after such an unexpected exception and continue sending the next batches of spans.

**What did you see instead?**
After this error, the exporter was not able to further send any spans until the process was restarted.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-exporter-jaeger-thrift
Version: 1.11.0
How did you reference these artifacts? In our bazel build: 
```
java_library(
   (...)
   deps = [
      "@common_deps//:io_opentelemetry_opentelemetry_exporter_jaeger_thrift",
```
**Environment**
Compiler: Azul Zulu OpenJDK 11
OS: CentOS 8
Runtime (if different from JDK above): Zulu 8.59.0.14-SA-linux64
OS (if different from OS compiled on): Photon OS 3.0

**Comment by jkwatson** [comment]
@nevenamanova are you able to provide a PR with the fix for this?

**Comment by nevenamanova** [comment]
Hi! No, I have not worked on a fix actually. On our side I worked-around it by setting the `MaxExportBatchSize` of the `BatchSpanProcessor` to a small number - 10 spans per batch.

**Comment by jkwatson** [comment]
Since we are on the verge of deprecating/removing this exporter, due to Jaeger no longer supporting the underlying technology, I think it's unlikely that we'll patch this.

**Comment by breedx-splk** [comment]
@nevenamanova are you able to use native otel OTLP exporter to send to jaeger instead?

**Comment by nevenamanova** [comment]
> @nevenamanova are you able to use native otel OTLP exporter to send to jaeger instead?

We will be moving to native OTLP in the future, yes. Since Jaeger is no longer supported, I guess you can close the ticket. Thanks!
