### ISSUE TITLE
java.lang.NoSuchFieldException: No field producerIndex in class Ld/a/d/a/a/a/h; (declaration of 'd.a.d.a.a.a.h'  )

### ISSUE THREAD

**Issue by SamirJobAtBharti** [open-telemetry/opentelemetry-java#4776]
```
FATAL EXCEPTION: main
                                                                                                    Process:
, PID: 25861
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(SourceFile:27)
                                                                                                    	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(SourceFile:83)
                                                                                                    	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(SourceFile:147)
                                                                                                    	at .activities.ActivityMain.openTelemetry(SourceFile:244)
                                                                                                    	at activities.ActivityMain.onCreate(SourceFile:232)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8086)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8074)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:213)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8178)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
                                                                                                    Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field producerIndex in class Ld/a/d/a/a/a/h; (declaration of 'd.a.d.a.a.a.h' appears in /data/app/com.zoodel.kz.staging_main-U1F68FFBSX-Cuf0YM6sZxg==/base.apk!classes3.dex)
                                                                                                    	at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(SourceFile:111)
                                                                                                    	at d.a.d.a.a.a.h.<clinit>(SourceFile:48)
                                                                                                    	at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(SourceFile:27) 
                                                                                                    	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(SourceFile:83) 
                                                                                                    	at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(SourceFile:147) 
                                                                                                    	at activities.ActivityMain.openTelemetry(SourceFile:244) 
                                                                                                    	at.ActivityMain.onCreate(SourceFile:232) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8086) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8074) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107) 
                                                                                                    	at android.os.Looper.loop(Looper.java:213) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8178) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
                                                                                                    Caused by: java.lang.NoSuchFieldException: No field producerIndex in class Ld/a/d/a/a/a/h; (declaration of 'd.a.d.a.a.a.h' appears in /data/app/com.zoodel.kz.staging_main-U1F68FFBSX-Cuf0YM6sZxg==/base.apk!classes3.dex)
                                                                                                    	at java.lang.Class.getDeclaredField(Native Method)
                                                                                                    	at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(S
```

**Comment by jkwatson** [comment]
Can you provide a little more detail?

**Comment by SamirJobAtBharti** [comment]
Hello @jkwatson,

i have added below in my app and it gives me exception( written above)

```
Resource resource = Resource.getDefault()
                    .merge(Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, "logical-service-name")));

            SdkTracerProvider sdkTracerProvider = SdkTracerProvider.builder()
                    .addSpanProcessor(BatchSpanProcessor.builder(OtlpGrpcSpanExporter.builder().build()).build())
                    .setResource(resource)
                    .build();

            SdkMeterProvider sdkMeterProvider = SdkMeterProvider.builder()
                    .registerMetricReader(PeriodicMetricReader.builder(OtlpGrpcMetricExporter.builder().build()).build())
                    .setResource(resource)
                    .build();

            OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
                    .setTracerProvider(sdkTracerProvider)
                    .setMeterProvider(sdkMeterProvider)
                    .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
                    .buildAndRegisterGlobal();

            Tracer tracer =
                    openTelemetry.getTracer("instrumentation-library-name", "1.0.0");

            Span span = tracer.spanBuilder("my span").startSpan();

            try (Scope ss = span.makeCurrent()) {
                Timber.d(ss.toString());
            } catch (Exception e){
                DataController.logException(e);
            }finally {
                span.end();
            }

```

**Comment by jkwatson** [comment]
Environment? JDK version? Dependencies being used? We need some information to help debug issues.

**Comment by jkwatson** [comment]
It looks like this is some kind of Android app, is that right? Make sure you have core-library desugaring enabled, as otel uses java 8 constructs extensively.

**Comment by SamirJobAtBharti** [comment]
@jkwatson 

i have added below dependency in my gradle file and add above code. Then i tried to run app. it gives me crash with above exception.

```
 //opentelemetry
    implementation platform("io.opentelemetry:opentelemetry-bom:1.18.0")
    implementation platform('io.opentelemetry:opentelemetry-bom-alpha:1.18.0-alpha')

    implementation('io.opentelemetry:opentelemetry-api')
    implementation('io.opentelemetry:opentelemetry-semconv')
    implementation('io.opentelemetry:opentelemetry-sdk-extension-autoconfigure')

    implementation('io.opentelemetry:opentelemetry-exporter-otlp:1.18.0')
```

**Comment by jkwatson** [comment]
Can you send your whole build.gradle? There are other steps for desugaring aside from just adding the library. It might also be good to turn off your code obfuscation to see the actual stack trace.

**Comment by mateuszrzeszutek** [comment]
Hey @SamirJobAtBharti ,
What version of Android Gradle Plugin are you using? If you want to use the 2.0 version of `desugar_jdk_libs` you have to use the beta 7.4 AGP: https://developer.android.com/studio/write/java8-support#library-desugaring
Have you tried using 1.X version of `desugar_jdk_libs` instead?
