### ISSUE TITLE
Error when using in-memory exporter for metrics

### ISSUE THREAD

**Issue by EricBuist** [open-telemetry/opentelemetry-java#5213]
**Describe the bug**
I am trying to use io.opentelemetry:opentelemetry-exporters-inmemory:0.9.1 to test spans and metrics. While this worked for spans using OpenTelemetry API 1.22.0, this fails for metrics with an AbstractMethodError.

**Steps to reproduce**
Create an OpenTelemetry object using the in-memory exporters, e.g.,

    InMemorySpanExporter spanExporter = InMemorySpanExporter.create();
    InMemoryMetricExporter metricExporter = InMemoryMetricExporter.create();
        Resource resource = Resource.getDefault()
            .merge(Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, "test")));
        SdkTracerProvider tracerProvider = SdkTracerProvider.builder()
            .addSpanProcessor(SimpleSpanProcessor.create(spanExporter))
            .setResource(resource)
            .build();
        SdkMeterProvider meterProvider = SdkMeterProvider.builder()
            // Causes errors, seems the metric exporter doesn't fully implement the interface.
            .registerMetricReader(PeriodicMetricReader.builder(metricExporter).build())
            .setResource(resource)
            .build();
        OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
            .setTracerProvider(tracerProvider)
            .setMeterProvider(meterProvider)
            .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
            .build();

Get a Meter, create at least one metric (e.g., an histogram), and record a value.

**What did you expect to see?**
The in-memory metrics exporter should record the metric and allow the testing code to access information about all recorded metrics.

**What did you see instead?**
An exception that lets me believe something changed in the API, not aligning with the in-memory exporter's implementation.

java.lang.AbstractMethodError: Receiver class io.opentelemetry.exporters.inmemory.InMemoryMetricExporter does not define or inherit an implementation of the resolved method 'io.opentelemetry.sdk.metrics.data.AggregationTemporality getAggregationTemporality(io.opentelemetry.sdk.metrics.InstrumentType)' of interface io.opentelemetry.sdk.metrics.export.MetricExporter.
 at io.opentelemetry.sdk.metrics.export.PeriodicMetricReader.getAggregationTemporality(PeriodicMetricReader.java:69)
 at io.opentelemetry.sdk.metrics.internal.state.DefaultSynchronousMetricStorage.(DefaultSynchronousMetricStorage.java:61)
 at io.opentelemetry.sdk.metrics.internal.state.SynchronousMetricStorage.create(SynchronousMetricStorage.java:57)
 at io.opentelemetry.sdk.metrics.internal.state.MeterSharedState.registerSynchronousMetricStorage(MeterSharedState.java:145)
 at io.opentelemetry.sdk.metrics.AbstractInstrumentBuilder.buildSynchronousInstrument(AbstractInstrumentBuilder.java:80)
 at io.opentelemetry.sdk.metrics.SdkLongHistogram$SdkLongHistogramBuilder.build(SdkLongHistogram.java:123)
 at io.opentelemetry.sdk.metrics.SdkLongHistogram$SdkLongHistogramBuilder.build(SdkLongHistogram.java:97)
 ..

**What version and what artifacts are you using?**
OpenTelemetry API 1.22.0
OpenTelemetry in-memory exporters 0.9.1 (latest available on Maven central)

How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

**Environment**
Compiler: OpenJDK 17
OS: Ubuntu 22.04
Runtime (if different from JDK above): Same as above OpenJDK
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

I need a way to verify that the instrumented code properly generate spans and metrics. I used to use MockTracer with OpenTracing, and read that in-memory exporter is the replacement option. For Micrometer testing, I used the SimpleMeterRegistry, but now it seems there is no obvious ways to test metrics.

**Comment by jkwatson** [comment]
yes, there is no reason that an artifact from 0.9.1 would be expected to work at this point against 1.22.0. The InMemoryMetricExporter now resides in the sdk-testing artifact. 

``` 
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-sdk-testing</artifactId>
        <version>1.22.0</version>
      </dependency>
```

**Comment by EricBuist** [comment]
Thanks. This works. Not sure I didn't check enough or if it is a gap in the documentation, but at least there is a simple solution.
