### ISSUE TITLE
GraalVM native-image: NoSuchFieldException: producerIndex - runtime hints missing?

### ISSUE THREAD

**Issue by colin-riddell** [open-telemetry/opentelemetry-java#5338]
**Describe the bug**
When running Spring boot application built with Java17  graalvm 22.3 using AOT native-image, the application fails to start due to `java.lang.NoSuchFieldException: producerIndex`

**Steps to reproduce**
* Clean Spring Boot 3.0.4 project from start.spring.io with:
  *  Dependencies:
```
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	runtimeOnly 'com.h2database:h2'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	implementation 'io.micrometer:micrometer-observation'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel:1.1.0-M2'
	implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
```
  * OTEL config:
```java
@Configuration
public class OpenTelemetryConfig {

	@Value("${otel.exporter.otlp.traces.endpoint:http://someotelcollector}")
	private String tracesEndpoint;

	@Bean
	public SpanExporter spanExporter() {
		return OtlpHttpSpanExporter.builder().setEndpoint(tracesEndpoint).build();
	}
}

```

**What did you expect to see?**
My understanding is that opentelemetry has native-image support. So I'd expect the application to start without crashing or throwing an exception. At the very least, a better tip on which native build compilation hints are needed to make it work.

**What did you see instead?**

The application fails to start with the trace:

```

Mar 31 10:24:51.836
at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107) ~[na:na]
at java.base@17.0.6/java.lang.Class.getDeclaredField(DynamicHub.java:961) ~[nativedemo:na]
Caused by: java.lang.NoSuchFieldException: producerIndex
at io.opentelemetry.internal.shaded.jctools.queues.MpscArrayQueueProducerIndexField.<clinit>(MpscArrayQueue.java:48) ~[nativedemo:1.19.0]
at io.opentelemetry.internal.shaded.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111) ~[na:na]
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]

at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[nativedemo:6.0.6]
at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[nativedemo:6.0.6]
at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[nativedemo:6.0.6]
at org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration__BeanDefinitions.lambda$getOtelSpanProcessorInstanceSupplier$5(OpenTelemetryAutoConfiguration__BeanDefinitions.java:127) ~[na:na]
at org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration.otelSpanProcessor(OpenTelemetryAutoConfiguration.java:124) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[na:na]
at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511) ~[nativedemo:na]
at java.base@17.0.6/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
at org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration.buildBatchSpanProcessor(OpenTelemetryAutoConfiguration.java:128) ~[nativedemo:na]
at io.opentelemetry.sdk.trace.export.BatchSpanProcessorBuilder.build(BatchSpanProcessorBuilder.java:147) ~[na:na]
at io.opentelemetry.sdk.trace.export.BatchSpanProcessor.<init>(BatchSpanProcessor.java:83) ~[na:na]
at io.opentelemetry.sdk.trace.internal.JcTools.newFixedSizeQueue(JcTools.java:27) ~[na:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
at java.base@17.0.6/java.lang.Class.ensureInitialized(DynamicHub.java:528) ~[nativedemo:na]
Caused by: java.lang.ExceptionInInitializerError: null
... 136 common frames omitted
at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:334) ~[na:na]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1225) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]
at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[nativedemo:6.0.6]
at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[nativedemo:6.0.6]
at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[nativedemo:6.0.6]
at org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration__BeanDefinitions.lambda$getOtelSdkTracerProviderInstanceSupplier$2(OpenTelemetryAutoConfiguration__BeanDefinitions.java:71) ~[na:na]
at org.springframework.boot.actuate.autoconfigure.tracing.OpenTelemetryAutoConfiguration.otelSdkTracerProvider(OpenTelemetryAutoConfiguration.java:105) ~[nativedemo:na]
at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.orderedStream(DefaultListableBeanFactory.java:2125) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.resolveStream(DefaultListableBeanFactory.java:2131) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1363) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1431) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1585) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1628) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1157) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1210) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1236) ~[nativedemo:6.0.6]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'otelSpanProcessor': Instantiation of supplied bean failed
... 121 common frames omitted
at org.springframework.beans.factory.aot.BeanInstanceSupplier.resolveArgument(BeanInstanceSupplier.java:334) ~[na:na]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1325) ~[nativedemo:6.0.6]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1405) ~[nativedemo:6.0.6]
```

**What version and what artifacts are you using?**
`opentelemetry-exporter-otlp` `1.19.0`
Referenced via build.gradle as above

**Environment**
Compiler: "Graalvm 22.3"
OS: AMI container

**Additional context**
I'd simply like to send traces from my native app to otel collector.
I see this was previously reported, but closed with no clear documented actions to take to fix - or even help given.

**Comment by colin-riddell** [comment]
Hey @mateuszrzeszutek  - Oh cool. :D thanks will give that a try and report back

**Comment by colin-riddell** [comment]
hey @mateuszrzeszutek  - thanks again for the pointers. I'm unable to get my gradle dependencies to use 1.24.0. All seem to point to 1.19.0 for some reason. 
Am I mistaken in thinking that the bom dep is for making sure all sub-dependencies are pointing to the same version?

**Comment by jack-berg** [comment]
> All seem to point to 1.19.0 for some reason.

@colin-riddell I've come across this before. If you use the [io.spring.dependency-management](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/), it brings in dependencies in a way that conflicts and overrides our opentelemetry-bom. I.e. I was using opentelemetry-bom:1.22.0 and yet opentelemetry-api and other artifacts were resolving to 1.19.0.

I got around it by bailing on the io.spring.dependency-management plugin and instead just depending on the spring boot BOM like [this](https://github.com/newrelic/newrelic-opentelemetry-examples/pull/258/commits/46571423558a46a49229617f5872c1135f8c9490#diff-21bc7265f74c0805ef365c54fd9e2696b565e660a8f7237ecd7eb2c226b4b6b5). There's also probably an idiomatic way to do this with the `io.spring.dependency-management` plugin, but not sure what that is off the top of my head.

**Comment by colin-riddell** [comment]
nice one @jack-berg  - I'll take a look. thanks 👍🏻

**Comment by colin-riddell** [comment]
Hey @jack-berg your tip on the spring-boot BOM worked perfectly. Ideally, we wouldn't need to do that to make it work.
I take it this is happening due to spring boot's version  of opentelemetry-java being `1.19.0`?
