### ISSUE TITLE
Cannot Able to Build because of Bean creation Exception

### ISSUE THREAD

**Issue by aravindMylsamy** [open-telemetry/opentelemetry-java#5462]
When I try to run the code it is showing the following error

```
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'openTelemetryConfig': Invocation of init method failed

at
app//org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:196)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
`


```
**Below is the code**

```

@Configuration
public class OpenTelemetryConfig {


    @Bean
    public OpenTelemetry openTelemetry() {
        return GlobalOpenTelemetry.get();
    }

    @Value("${jaeger.endpoint}")
    String endpoint;

    @Value("${service.name}")
    String serviceName;

    @Value("${jaeger.enabled}")
    boolean jaegerEnabled;

    @PostConstruct
    public void setUpOpenTelemetry() {
        Resource serviceNameResource =
                Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, serviceName));

        JaegerGrpcSpanExporter jaegerExporter = JaegerGrpcSpanExporter.builder()
                .setEndpoint(endpoint)
                .build();

        SdkTracerProviderBuilder tracerProviderBuilder = SdkTracerProvider.builder()
                .setResource(Resource.getDefault().merge(serviceNameResource));

        SdkTracerProvider tracerProvider = !jaegerEnabled ? tracerProviderBuilder.build() : tracerProviderBuilder
                .addSpanProcessor(SimpleSpanProcessor.create(jaegerExporter))
                .build();

        OpenTelemetrySdk.builder()
                .setTracerProvider(tracerProvider)
                .setPropagators(ContextPropagators.create(W3CTraceContextPropagator.getInstance()))
                .buildAndRegisterGlobal();
    }
}

```

**Comment by jack-berg** [comment]
Please include more of the stack trace. The portion you included doesn't include any of the details of what went wrong initializing OpenTelemetrySdk.

**Comment by jkwatson** [comment]
And, just FYI, we strongly recommend against initializing the global and using it unless you have an extremely good reason why you can't just use an instance of OpenTelemetry.

**Comment by aravindMylsamy** [comment]
Thanks for all of the responses, it was due to some dependency issues in gradle file solved now.
