### ISSUE TITLE
JaegerRemoteSampler does not work with adaptive sampling when number of operation strategies is zero

### ISSUE THREAD

**Issue by dssysolyatin** [open-telemetry/opentelemetry-java#5468]
**Describe the bug**
Jaeger remote sampler does not work with adaptive sampling when number of operation strategies is zero.
I believe that problem is inside the following `if` statement.

```
    if (operationSampling.strategies.size() > 0) {
      Sampler defaultSampler =
          Sampler.traceIdRatioBased(operationSampling.defaultSamplingProbability);
      return Sampler.parentBased(
          new PerOperationSampler(defaultSampler, operationSampling.strategies));
    }
```

Even if `operationSampling.strategies.size()` is zero, jaeger-collector can return `defaultSamplingProbability` that should be applied for all operations. From https://github.com/jaegertracing/jaeger-idl/blob/main/proto/api_v2/sampling.proto:

```
// defaultSamplingProbability is the sampling probability for spans that do not match
  // any of the perOperationStrategies.
  double defaultSamplingProbability = 1;
```

Fox example: In my environment jaerger-collector returns defaultSamplingProbability = 0.001 and empty perOperationStrategies

**Steps to reproduce**
1. Run jaeger-collector in adaptive sampling mode
2. Use JaegerRemoteSampler

**What did you expect to see?**
Adaptive sampling should work.

**What did you see instead?**
```
WARNING: Failed to update sampler
java.lang.AssertionError: unrecognized sampler type
	at io.opentelemetry.sdk.extension.trace.jaeger.sampler.JaegerRemoteSampler.updateSampler(JaegerRemoteSampler.java:98)
	at io.opentelemetry.sdk.extension.trace.jaeger.sampler.JaegerRemoteSampler.getAndUpdateSampler(JaegerRemoteSampler.java:74)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
```

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk-extension-jaeger-remote-sampler`
Version: `v1.26.0`
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)

**Environment**
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**Comment by dssysolyatin** [comment]
Looks like adaptive sampling does not work at all. The issue describes in #4860, I close this issue as duplicate.
