### ISSUE TITLE
StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.trace.v1.TraceService

### ISSUE THREAD

**Issue by FrankCy** [open-telemetry/opentelemetry-java#5615]
How to fix this problem?

[opentelemetry.auto.trace 2023-07-10 15:29:33:571 +0800] [grpc-default-executor-0] WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: UNIMPLEMENTED: unknown service opentelemetry.proto.collector.trace.v1.TraceService
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:515)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)

**Comment by jack-berg** [comment]
The server you're exporting to doesn't support spans. You'll need to work with whoever operates that server to understand if this is expected or not.

**Comment by FrankCy** [comment]
OK, THX.
