### ISSUE TITLE
Local Traces Work but Issues with OTEL Exporter

### ISSUE THREAD

**Issue by kuro337** [open-telemetry/opentelemetry-java#5895]
I am following the Manual Instrumentation for java example - and to see the Traces locally it works

https://opentelemetry.io/docs/instrumentation/java/manual/

Now I have been trying  to export the traces directly to a Tempo Backend. 
For example I have this yaml file that handles a seperate isolated app that sends traces correctly to the backend  using HTTP (unrelated to this problem - but including to show that the same Tempo endpoint I am using here is being used for the main issues below ).

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-example-app-tempo
  template:
    metadata:
      labels:
        app: agent-example-app-tempo
    spec:
      containers:
        - name: app-tempo
          image: ghcr.io/kuro337/java-otel-agent:latest
          env:
            - name: OTEL_SERVICE_NAME
              value: "agent-example-app-tempo"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector-tempo:4317"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret
```

## Current Issue 

- Trying to modify the official example to send Traces to the `Tempo backend` instead of `stdout`

For the current app - when I run it just to log traces to `stdout` it shows tracing locally - using these commands to run `jar`

```bash
gradle assemble
env \
OTEL_SERVICE_NAME=dice-server \
OTEL_TRACES_EXPORTER=logging \
OTEL_METRICS_EXPORTER=logging \
OTEL_LOGS_EXPORTER=logging \
java -jar ./build/libs/OTEL-Manual-1.0.jar
```

Traces Showing -

```bash
2023-10-09T16:02:21.357-04:00  INFO 10261 --- [nio-8080-exec-1] k.o.otel.controller.RollController       : Anonymous player is rolling the dice: [5,
 2, 5, 4, 3, 6, 6, 3, 6, 1, 4, 3]
2023-10-09T16:02:21.361-04:00  INFO 10261 --- [nio-8080-exec-1] i.o.e.logging.LoggingSpanExporter        : 'rollTheDice' : dd453e944a285df06ba313b95
fb872c2 e13a474d597fe99a INTERNAL [tracer: kuro.observability.otel.controller.RollController:0.1.0] {}
2023-10-09T16:02:51.259-04:00  INFO 10261 --- [nio-8080-exec-2] k.o.otel.controller.RollController       : Anonymous player is rolling the dice: [3,
 6, 3, 1, 1, 3, 1, 6, 4, 6, 5, 1]
2023-10-09T16:02:51.259-04:00  INFO 10261 --- [nio-8080-exec-2] i.o.e.logging.LoggingSpanExporter        : 'rollTheDice' : f67b9e770519dac84d7294ac6
2a8fb37 7c6700a927d8e482 INTERNAL [tracer: kuro.observability.otel.controller.RollController:0.1.0] {}
```

However when I want to export these logs to the endpoint - my understanding is since I am using the AutoConfig we can just  add the dependency `implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.30.1")` - and set the ENV  variables to send Traces to the endpoint

but when I add that dependency and use these Variables

```yaml
          env:
            - name: OTEL_SERVICE_NAME
              value: "dice-server"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector-tempo:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
```

- Full build.gradle.kts

```kts
plugins {
    id("java")
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.9.20-Beta2"
}

group = "kuro.observability.otel"
version = "1.0"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    implementation("org.springframework.boot:spring-boot-starter-web")

    // OpenTelemetry dependencies
    implementation("io.opentelemetry:opentelemetry-api:1.30.1")
    implementation("io.opentelemetry:opentelemetry-sdk:1.30.1")
    implementation("io.opentelemetry:opentelemetry-sdk-metrics:1.30.1")
    implementation("io.opentelemetry:opentelemetry-exporter-logging:1.30.1")
    implementation("io.opentelemetry:opentelemetry-semconv:1.30.1-alpha")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.30.1")
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:1.30.1")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp:1.30.1")


    // Kotlin
    implementation(kotlin("stdlib-jdk8"))
}

tasks.test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(19)
}
```
 - Full Deployment.yaml file
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-server
  template:
    metadata:
      labels:
        app: dice-server
    spec:
      containers:
        - name: dice-server
          image: ghcr.io/kuro337/jar-trace-simple-tempo:latest
          env:
            - name: OTEL_SERVICE_NAME
              value: "dice-server"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://collector-tempo:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"

          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-secret
```

- But my app is crashing when I try to have the `jar` export to the backend instead of `stdout`

```bash
 kubectl logs dice-server-848ff76ccd-smfhh                             
2023-10-09T20:11:02.631Z  INFO 1 --- [           main] k.o.otel.app.DiceApplication             : Starting DiceApplication v1.0 using Java 19.0.2 wi
th PID 1 (/app/app.jar started by root in /app)
2023-10-09T20:11:02.636Z  INFO 1 --- [           main] k.o.otel.app.DiceApplication             : No active profile set, falling back to 1 default p
rofile: "default"
2023-10-09T20:11:03.455Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)      
2023-10-09T20:11:03.462Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-10-09T20:11:03.462Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.8]   
2023-10-09T20:11:03.521Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-10-09T20:11:03.522Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization complet
ed in 832 ms
2023-10-09T20:11:03.596Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initializatio
n - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rollController' def
ined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/kuro/observability/otel/controller/RollController.class]: Unsatisfied dependency expressed thr
ough constructor parameter 0: Error creating bean with name 'openTelemetry' defined in kuro.observability.otel.app.DiceApplication: Failed to instan
tiate [io.opentelemetry.api.OpenTelemetry]: Factory method 'openTelemetry' threw exception with message: io/opentelemetry/exporter/internal/http/Htt
pExporterBuilder
2023-10-09T20:11:03.598Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-09T20:11:03.610Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger :

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-10-09T20:11:03.626Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rollController' defined in URL [jar:file:/app/app.j
ar!/BOOT-INF/classes!/kuro/observability/otel/controller/RollController.class]: Unsatisfied dependency expressed through constructor parameter 0: Er
ror creating bean with name 'openTelemetry' defined in kuro.observability.otel.app.DiceApplication: Failed to instantiate [io.opentelemetry.api.Open
Telemetry]: Factory method 'openTelemetry' threw exception with message: io/opentelemetry/exporter/internal/http/HttpExporterBuilder
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.8.jar!
/:6.0.8]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.8.jar!
/:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:
1352) ~[spring-beans-6.0.8.jar!/:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1
189) ~[spring-beans-6.0.8.jar!/:6.0.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBe
```

Full Code for this is here including stdout and collector way
https://github.com/kuro337/OTEL-Manual

I was wondering if I was doing anything wrong? 

I would highly appreciate also if anyone could point me to any resources or Discords where folks are using Java with OpenTelemetry in a Kube native context! I wish to add Tracing and other Telemetry to my app - and control where it goes with Environment Variables. 

One more unrelated question is - for using  the separate .jar file as seen here - the Java Agent - https://opentelemetry.io/docs/instrumentation/java/automatic/ - is this meant to be used if we do not add any manual traces using spans, etc. within the app itself? If we are configuring the AutoSDK within my JAR and building it - and setting Traces - is the separate jar  also required - apologies for the beginner questions.

I am interested in Telemetry and the OpenTelemetry project and I want to learn how to include Telemetry as a part of my Development Workflow - where I typically write applications/services and then deploy them to servers/kube deployments. Thank you all for the help!

**Comment by daangn-rainn** [comment]
Did you fix this issue?

**Comment by trask** [comment]
I think that

```
id("io.spring.dependency-management") version "1.1.0"
```

may end up overriding some opentelemetry dependency versions

cc @jeanbisutti

**Comment by jeanbisutti** [comment]
@daangn-rainn Could you please share the code in a Github repo? In this way I could investigate the root cause. Thank you.

**Comment by jeanbisutti** [comment]
@kuro337 Could you please share your example with a Github repo to allow me to investigate? Thank you.
