### ISSUE TITLE
OTEL_EXPORTER_OTLP_PROTOCOL has no effect

### ISSUE THREAD

**Issue by NicolaeVasile1997** [open-telemetry/opentelemetry-java#6100]
Greetings. 

I am setting `export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"` and also trying to pass `-Dotel.exporter.otlp.protocol=http/protobuf` when running my `.jar` file. Logs indicate it is still trying to use gRPC (which is unsupported by DynaTrace)

I have a Spring Boot 2.7 application. I am following these two docs for implementing opentelemetry:
https://opentelemetry.io/docs/instrumentation/java/exporters/#otlp-dependencies
https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/

I've taken the instruction of the former and excluded the `opentelemetry-exporter-sender-okhttp` from `opentelemetry-exporter-otlp` and included `opentelemetry-exporter-sender-jdk`. Now it is still trying to use gRPC:

(Not the full stack trace)
```
Caused by: java.lang.IllegalStateException: No GrpcSenderProvider found on classpath. Please add dependency on opentelemetry-exporter-sender-okhttp or opentelemetry-exporter-sender-grpc-upstream
	at io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.resolveGrpcSenderProvider(GrpcExporterBuilder.java:229)
	at io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder.build(GrpcExporterBuilder.java:156)
	at io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporterBuilder.build(OtlpGrpcSpanExporterBuilder.java:203)
	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.otlp.OtlpSpanExporterAutoConfiguration.otelOtlpGrpcSpanExporter(OtlpSpanExporterAutoConfiguration.java:56)
	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.otlp.OtlpSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$96d95dd.CGLIB$otelOtlpGrpcSpanExporter$0(<generated>)
	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.otlp.OtlpSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$96d95dd$$FastClassBySpringCGLIB$$97d37845.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at io.opentelemetry.instrumentation.spring.autoconfigure.exporters.otlp.OtlpSpanExporterAutoConfiguration$$EnhancerBySpringCGLIB$$96d95dd.otelOtlpGrpcSpanExporter(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 81 common frames omitted
```

I'll see about producing a minimal project to duplicate the but I wont be able to do it expeditiously.

I expect that setting `OTEL_EXPORTER_OTLP_PROTOCOL` to `http/protobuf` would prevent gRPC from being used. I also expected that excluding the `sender-okhttp` dependency per the docs, and including `sender-jdk` would prevent gRPC from being used.

Instead the application insists on using gRPC even and will even throw an exception instead of choosing another protocol

Here is a shortened version of my pom that should have all otel related dependencies included:
```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.opentelemetry</groupId>
				<artifactId>opentelemetry-bom</artifactId>
				<version>1.32.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>io.opentelemetry.instrumentation</groupId>
				<artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
				<version>1.32.0-alpha</version>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>


	<dependencies>
		<dependency>
			<groupId>io.opentelemetry.instrumentation</groupId>
			<artifactId>opentelemetry-spring-boot-starter</artifactId>
			<version>1.32.0-alpha</version>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry.instrumentation</groupId>
			<artifactId>opentelemetry-logback-appender-1.0</artifactId>
			<version>1.32.0-alpha</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk-extension-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk-extension-autoconfigure-spi</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-otlp</artifactId>
			<exclusions>
				<exclusion>
					<groupId>io.opentelemetry</groupId>
					<artifactId>opentelemetry-exporter-sender-okhttp</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-exporter-sender-jdk</artifactId>
			<version>1.32.0-alpha</version>
		</dependency>
	</dependencies>
```

**Environment**
Compiler: openjdk 11.0.20.1 2023-08-24
OS: MacOS 13.6

**Additional context**
A similar issue happened here:
https://github.com/open-telemetry/opentelemetry-python/issues/2586

**Comment by NicolaeV** [comment]
A semi-related question, [in this doc it states](https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/): "The OpenTelemetry starter is compatible with Spring Boot 2.0 and 3.0, and Spring native"

But the [readme for the starter](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md) says: "Replace SPRING_VERSION with the version of spring you're using. Minimum version: 3.1"

Does that imply there is no starter support for Spring Boot 2? or are certain features limited? If its the latter, which features are incompatible? What compatible with 2.7?

**Comment by pirgeo** [comment]
I think the issue you are seeing is caused by the fact that the current release of the autoconfigure package always creates a OtlpGrpc exporter: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/release/v1.30.x/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/exporters/otlp/OtlpLoggerExporterAutoConfiguration.java#L30. It seems like it has been updated since then and should be fixed in the next release (see the code on main for the same class now: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/exporters/otlp/OtlpLoggerExporterAutoConfiguration.java). 

In the meantime, what you could do is disable the autoconfigured exporters in your `application.properties` file:
```java
otel.exporter.otlp.traces.enabled=false
otel.exporter.otlp.metrics.enabled=false
otel.exporter.otlp.logs.enabled=false
```
and manually create beans for the OtlpHttp exporters:
```java
@SpringBootApplication
public class MyApplication {
    @Bean
    OtlpHttpSpanExporter spanExporter() {
		 // configure these with the right endpoint / headers etc. here if you need to, otherwise it will export HTTP/protobuf to localhost:4318/v1/traces
         return OtlpHttpSpanExporter.getDefault();
    }

    @Bean
    OtlpHttpMetricExporter metricExporter() {
        return OtlpHttpMetricExporter.getDefault();
    }

    @Bean
    OtlpHttpLogRecordExporter logExporter() {
        return OtlpHttpLogRecordExporter.getDefault();
    }

    public static void main(String[] args) {
        SpringApplication.run(MyApplication.class, args);
    }
}
```

Also, if you want to export logs, make sure to setup logback/log4j as described in https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/#logging-instrumentation. This will take all the Spring Boot logs and forward them via OTLP. 

Ah, one more thing. I think you don't need to add all of these dependencies, this was enough for me to get the above example working: 

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>1.33.0</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
                <version>1.32.0-alpha</version>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-spring-boot-starter</artifactId>
            <version>1.32.0-alpha</version>
        </dependency>
    </dependencies>
```

The `opentelemetry-spring-boot-starter` contains everything you need.
