### ISSUE TITLE
Is opentelemetry-exporter-otlp-metrics deprecated?

### ISSUE THREAD

**Issue by programmatix** [open-telemetry/opentelemetry-java#6173]
**Describe the bug**
The latest build of opentelemetry-exporter-otlp-metrics I can find is 1.14.0 published in May 2022.  It doesn't seem to be compatible with current versions of the OpenTelemetry APIs, as when I try to use it together with 1.31.0, I get this error:

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Method 'io.opentelemetry.exporter.internal.grpc.GrpcExporterBuilder io.opentelemetry.exporter.internal.grpc.GrpcExporter.builder(java.lang.String, long, java.net.URI, java.util.function.Supplier, java.lang.String, java.lang.String)' must be Methodref constant
	at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporterBuilder.<init>(OtlpGrpcMetricExporterBuilder.java:44)
	at io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter.builder(OtlpGrpcMetricExporter.java:43)
	at org.example.Main.metrics(Main.java:107)
	at org.example.Main.main(Main.java:45)
```

This looks to be related to[ this commit](https://github.com/open-telemetry/opentelemetry-java/blob/a3bf8af42ebdeee2b7bb513464daa214af1f633e/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporter.java) which removed GrpcExporter.builder().

Is this jar deprecated?  Should I be using an alternative?

**Steps to reproduce**
A simplified version of my project is:

pom.xml:

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>1.31.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp-metrics</artifactId>
            <version>1.14.0</version>
        </dependency>
```
And code:
```
        MetricExporter exporter = OtlpGrpcMetricExporter.builder()
                .setCompression("gzip")
                .setEndpoint("http://localhost:4317")
                .build();

        SdkMeterProvider sdkMeterProvider = SdkMeterProvider.builder()
                .setResource(Resource.getDefault()
                        .merge(Resource.builder()
                                .put("service.name", "TestService")
                                .build()))
                .registerView(InstrumentSelector.builder().setType(InstrumentType.HISTOGRAM).build(),
                        View.builder().setAggregation(Aggregation.explicitBucketHistogram(List.of(
                                100000.0,
                                250000.0,
                                500000.0,
                                1000000.0,
                                10000000.0,
                                100000000.0,
                                1000000000.0,
                                10000000000.0))).build())
                .registerMetricReader(PeriodicMetricReader.builder(exporter).setInterval(Duration.ofSeconds(10)).build())
                .build();

        OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
                .setMeterProvider(sdkMeterProvider)
                .buildAndRegisterGlobal();
```

**Comment by jack-berg** [comment]
> The latest build of opentelemetry-exporter-otlp-metrics I can find is 1.14.0 published in May 2022. It doesn't seem to be compatible with current versions of the OpenTelemetry APIs, as when I try to use it together with 1.31.0, I get this error:

`opentelemetry-exporter-otlp-metrics` was merged into `opentelemetry-exporter-otlp` in the [1.15.0](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.15.0) release. We consider this an allowable change because while the artifact coordinates changed, the code itself was backwards compatible. See our [compatibility requirements](https://github.com/open-telemetry/opentelemetry-java/blame/main/VERSIONING.md#L45-L48) for more info.

**Comment by programmatix** [comment]
Hi @jack-berg, thank you for your response.  I do use the BOM to keep versions aligned, but of course couldn't for opentelemetry-exporter-otlp-metrics specifically since it's no longer in the 1.31.0 BOM.  Now I know everything's moved over to opentelemetry-exporter-otlp I'll start using that.
