### ISSUE TITLE
Inconsistent metric deduplication in Otel2PrometheusConverter

### ISSUE THREAD

**Issue by nluk** [open-telemetry/opentelemetry-java#6277]
**Describe the bug**
Prometheus MetricSnapshots constructor throws because of duplicated metric names. This is a part of the `Otel2PrometheusConverter::convert` call.
```java
An Exception occurred while scraping metrics: java.lang.IllegalArgumentException: logback_events: duplicate metric name
	at io.prometheus.metrics.model.snapshots.MetricSnapshots.<init>(MetricSnapshots.java:43)
	at io.opentelemetry.exporter.prometheus.Otel2PrometheusConverter.convert(Otel2PrometheusConverter.java:112)
	at io.opentelemetry.exporter.prometheus.PrometheusMetricReader.collect(PrometheusMetricReader.java:56)
	at io.prometheus.metrics.model.registry.MultiCollector.collect(MultiCollector.java:26)
	at io.prometheus.metrics.model.registry.PrometheusRegistry.scrape(PrometheusRegistry.java:72)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.scrape(PrometheusScrapeHandler.java:112)
	at io.prometheus.metrics.exporter.common.PrometheusScrapeHandler.handleRequest(PrometheusScrapeHandler.java:53)
	at io.prometheus.metrics.exporter.httpserver.MetricsHandler.handle(MetricsHandler.java:43)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Steps to reproduce**
Create two MetricData objects with different `name`s, that resolve to the same `prometheusName` and run `convert`.

Testcase to reproduce the error: https://github.com/open-telemetry/opentelemetry-java/compare/main...nluk:opentelemetry-java:bug/prometheus-converter-duplicate-metric-name

**What did you expect to see?**

Hard to say really. Metrics of the same type may be merged, but the fact that there are two competing metrics `a.b` and `a_b` might indicate a misconfiguration.

**What did you see instead?**

The `Otel2PrometheusConverter::putOrMerge` [method](https://github.com/open-telemetry/opentelemetry-java/blob/91c4a1b88dc107979589566cdbc24b0c5abee3ea/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/Otel2PrometheusConverter.java#L464) uses `snapshot.getMetadata().getName()` as a unique map key. So `metric.name` and `metric_name` are two separate entries.

Prometheus compares sorted `snapshot.getMetadata().getPrometheusName()` [link](https://github.com/prometheus/client_java/blob/3fdba974aa96c8f2ebb89eee78787e2bd52c3042/prometheus-metrics-model/src/main/java/io/prometheus/metrics/model/snapshots/MetricSnapshots.java#L42) to find collisions. This means that `metric.name` and `metric_name` are both represented as `metric_name`, and a collision is detected.

**What version and what artifacts are you using?**
Artifacts: aws-opentelemetry-agent 1.32.1, so opentelemetry 1.32.1 [link](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/0a51f9386c8d2beca21d90e5d91e8527ae63aaaf/dependencyManagement/build.gradle.kts#L30) that targets otel-sdk 1.34.1

**Environment**
Compiler: Temurin-17.0.5+8
OS: Ubuntu 22.04

**Comment by jack-berg** [comment]
> Prometheus compares sorted snapshot.getMetadata().getPrometheusName() [link](https://github.com/prometheus/client_java/blob/3fdba974aa96c8f2ebb89eee78787e2bd52c3042/prometheus-metrics-model/src/main/java/io/prometheus/metrics/model/snapshots/MetricSnapshots.java#L42) to find collisions. This means that metric.name and metric_name are both represented as metric_name, and a collision is detected.

I think this `getName` vs. `getPrometheusName` is the key bit here. Its an oversight on our part to use `getName` for the keys of our map. Opening a PR to adjust it to use `getPrometheusName` everywhere.

But this won't completely solve the problem. Its still possible that `my.metric` and `my_metric` have overlapping series. I.e. both might have a series with attributes `{key=a}`. If this occurs, then the prometheus client will generate an error. I don't think `Otel2PrometheusConverter` should be responsible for this merging of series. Instead, if a user encounters this, they should use views to rename one of `my.metric` or `my_metric` such that the conflict doesn't occur.
