### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/sdk/internal/ScopeConfigurator

### ISSUE THREAD

**Issue by nagkumar** [open-telemetry/opentelemetry-java#6460]
```
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/sdk/internal/ScopeConfigurator
        at io.opentelemetry.sdk.logs.internal.LoggerConfig.configuratorBuilder(LoggerConfig.java:56)
        at io.opentelemetry.sdk.logs.SdkLoggerProviderBuilder.<init>(SdkLoggerProviderBuilder.java:38)       
        at io.opentelemetry.sdk.logs.SdkLoggerProvider.builder(SdkLoggerProvider.java:48)
        at com.teja.sb.otel.cfgs.OTelCFG.otelSdkLoggerProvider(OTelCFG.java:45)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$0.CGLIB$otelSdkLoggerProvider$1(<generated>)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.teja.sb.otel.cfgs.OTelCFG$$SpringCGLIB$$0.otelSdkLoggerProvider(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)  
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
        ... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.sdk.internal.ScopeConfigurator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)        
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 48 common frames omitted
[INFO] -----------------------------------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------------------------------- 
[INFO] Total time:  6.114 s
[INFO] Finished at: 2024-05-15T09:35:58+05:30
[INFO] ----------------------------------------------------------------------------------------------------- 
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.1.5:start (default-cli) on
 project wflux: Failed to connect to MBean server at port 9001: Could not invoke shutdown operation: Connection refused to host: 127.0.0.1; nested exception is:

```

**Comment by jkwatson** [comment]
Can you provide some more details here? What does your pom look like? What is this class, and what is it trying to do?  `com.teja.sb.otel.cfgs.OTelCFG`.

**Comment by nagkumar** [comment]
```
my pom is 

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>3.1.5</version>
	<relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.reactive.optl</groupId>
    <artifactId>wflux</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <description>Demo project for Spring Boot and OpenTelemetry</description>
    <properties>
	<java.version>17</java.version>
	<otel.version>1.31.0</otel.version>
    </properties>
    <dependencies>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-webflux</artifactId>
	</dependency>
	<dependency>
	    <groupId>org.springdoc</groupId>
	    <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
	    <version>2.5.0</version>
	</dependency>
	<dependency>
	    <groupId>org.springframework.boot</groupId>
	    <artifactId>spring-boot-starter-test</artifactId>
	    <scope>test</scope>
	</dependency>
	<dependency>
	    <groupId>io.micrometer</groupId>
	    <artifactId>micrometer-registry-otlp</artifactId>
	    <scope>runtime</scope>
	</dependency>
	<dependency>
	    <groupId>io.micrometer</groupId>
	    <artifactId>micrometer-tracing-bridge-otel</artifactId>
	    <version>1.3.0</version>
	</dependency>

	<dependency>
	    <groupId>org.projectlombok</groupId>
	    <artifactId>lombok</artifactId>
	    <optional>true</optional>
	</dependency>

	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-api</artifactId>
	    <version>${otel.version}</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-sdk</artifactId>
	    <version>${otel.version}</version>
	</dependency>

	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-common</artifactId>
	    <version>${otel.version}</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-otlp-common</artifactId>
	    <version>${otel.version}</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry</groupId>
	    <artifactId>opentelemetry-exporter-otlp</artifactId>
	    <version>${otel.version}</version>
	</dependency>

	<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-logback-appender-1.0</artifactId>
	    <version>${otel.version}-alpha</version>
	</dependency>
	<dependency>
	    <groupId>io.opentelemetry.instrumentation</groupId>
	    <artifactId>opentelemetry-instrumentation-api-semconv</artifactId>
	    <version>${otel.version}-alpha</version>
	</dependency>

	<dependency>
	    <groupId>io.netty</groupId>
	    <artifactId>netty-all</artifactId>
	</dependency>

	<dependency>
	    <groupId>org.jetbrains</groupId>
	    <artifactId>annotations</artifactId>
	    <version>24.1.0</version>
	</dependency>
    </dependencies>

    <build>
	<plugins>
	    <plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<configuration>
		    <excludes>
			<exclude>
			    <groupId>org.projectlombok</groupId>
			    <artifactId>lombok</artifactId>
			</exclude>
		    </excludes>
		</configuration>
	    </plugin>
	</plugins>
    </build>
</project>

```

```
package com.teja.sb.otel.cfgs;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.context.propagation.ContextPropagators;
import io.opentelemetry.exporter.otlp.logs.OtlpGrpcLogRecordExporter;
import io.opentelemetry.instrumentation.logback.appender.v1_0.OpenTelemetryAppender;
import io.opentelemetry.sdk.OpenTelemetrySdk;
import io.opentelemetry.sdk.logs.LogRecordProcessor;
import io.opentelemetry.sdk.logs.SdkLoggerProvider;
import io.opentelemetry.sdk.logs.SdkLoggerProviderBuilder;
import io.opentelemetry.sdk.logs.export.BatchLogRecordProcessor;
import io.opentelemetry.sdk.resources.Resource;
import io.opentelemetry.sdk.trace.SdkTracerProvider;
import io.opentelemetry.semconv.ResourceAttributes;
import org.jetbrains.annotations.NotNull;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.env.Environment;

import java.util.Objects;

@Configuration
public class OTelCFG
{
    @Bean
    OpenTelemetry openTelemetry(final SdkLoggerProvider aSDKLoggerProvider,
				final SdkTracerProvider aSDKTracerProvider,
				final ContextPropagators aContextPropagators)
    {
	final OpenTelemetrySdk openTelemetrySdk = OpenTelemetrySdk.builder()
								  .setLoggerProvider(aSDKLoggerProvider)
								  .setTracerProvider(aSDKTracerProvider)
								  .setPropagators(aContextPropagators)
								  .build();
	OpenTelemetryAppender.install(openTelemetrySdk);
	return openTelemetrySdk;
    }

    @Bean
    SdkLoggerProvider otelSdkLoggerProvider(final Environment aEnvironment,
					    final ObjectProvider<LogRecordProcessor> aLogRecordProcessors)
    {
	final String applicationName = aEnvironment.getProperty("spring.application.name", "app");
	final Resource resource = Resource.create(Attributes.of(ResourceAttributes.SERVICE_NAME, applicationName));
	final SdkLoggerProviderBuilder builder = SdkLoggerProvider.builder()
								  .setResource(Resource.getDefault().merge(resource));
	aLogRecordProcessors.orderedStream().forEach(builder::addLogRecordProcessor);
	return builder.build();
    }

    @Bean
    LogRecordProcessor otelLogRecordProcessor(@NotNull final ApplicationContext aApplicationContext)
    {
	return BatchLogRecordProcessor
		.builder(OtlpGrpcLogRecordExporter.builder()
						  .setEndpoint(
							  Objects.requireNonNull(aApplicationContext.getEnvironment()
												    .getProperty(
													    "mgmt.oltp.logs.export.url")))
						  .build())
		.build();
    }
}
```

this fails when 

	<otel.version>1.31.0</otel.version>

changed to the even 1.32.0 and above.. including the latest 1.38.0

some jar file issues

**Comment by jack-berg** [comment]
Can you check the resolved version of all your dependencies? I noticed you using spring, which we've seen is quite stubborn about the versions of opentelemetry artifacts it brings in. I suspect that you successfully upgraded some artifact versions, but not all, and opentelemetry-java artifacts all need to be kept in sync at the same version.

See this https://github.com/open-telemetry/opentelemetry-java/issues/6018#issuecomment-1828809517 for a few different ways people have found to override the version from spring dependency management.

**Comment by trask** [comment]
> See this [#6018 (comment)](https://github.com/open-telemetry/opentelemetry-java/issues/6018#issuecomment-1828809517) for a few different ways people have found to override the version from spring dependency management.

also check out https://opentelemetry.io/docs/languages/java/automatic/spring-boot/#dependency-management

**Comment by nagkumar** [comment]
Thank You it worked..

**Comment by nishuChandravanshi** [comment]
> lly marked as stale because it has been marked as needing author feedback and has not had any activity for 7 days. It will be closed if no further activity occur

hi how did it work can you pls share
